language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
sudo: false
script:
- sbt clean coverage test
after_success:
- sbt coveralls
env:
  global:
    secure: ZnPsND0BEHfo5q/3Jp2W3EfU+ie6U/4bMptVTTHaoXKgqBHEcfw2kZ+WEEcR16klpQtLZvvWEwm1yJc1pMnHcVcWkAe92HrA0VBOzJ1pf3USTxCWusXX+lEZpsi9gBD7YzSgNz6smfX/vrPio4LQ6GtczBFCWxuuodjpBwyTUU6+J1hAlXeiWzZG+/O552UEFR3SDIb2dX5DP4vODL/XNeAl1140atti2QveXDno4OcVdNh6X9xXzE1uDO99rOXLNAihIZkSshynSWaht0F7rTzPmGfRY/IjZfyLR2ddIpcml3DsSJ/f4tEpHNTAhN4+AGUv7/7sw93DFLQrE3lLKyDiITOui9X469yO/kur5ZITW6JENFwKOyNjWq0uePfrK5egBNITTFNNOQAw49CztDhTkAiLblfkXjgXcHdFSnBAuK2rqM7gSeqeeYsC4kTB4ZABfTOHcy14vACCRQDYV52Cq/d8XgLEMftznkdzn3otrykbfmE2E0A20QVRm1eHo+bZEi4jH05+uDlYmxXEhgrKcn0ZDk1uygrNZLwcrrakYWkD82QXXQNrh/T87f2O8ocypxezpHdKC585qjk+MbIkpl0VsieTnDPn/FRHKVxsBHhiRADuVPBp/yRmGXW7z3MkIsU6bWg2a4kKwjOyfEhUfQFk5fSTjlvZpSkSF4g=
